# Form implementation generated from reading ui file 'e:\A_Do_An_Endgames\Dev\eHealth_Version1.0_11_19_2021_1_58_pm_Debug\GUI\Design\UI_CTScanPatient.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CTScanPatient(object):
    def setupUi(self, CTScanPatient):
        CTScanPatient.setObjectName("CTScanPatient")
        CTScanPatient.resize(420, 483)
        CTScanPatient.setMinimumSize(QtCore.QSize(420, 483))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CTScanPatient)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CTScanPatient)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboCTScanType = QtWidgets.QComboBox(CTScanPatient)
        self.comboCTScanType.setMinimumSize(QtCore.QSize(268, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboCTScanType.setFont(font)
        self.comboCTScanType.setObjectName("comboCTScanType")
        self.comboCTScanType.addItem("")
        self.comboCTScanType.addItem("")
        self.comboCTScanType.addItem("")
        self.comboCTScanType.addItem("")
        self.horizontalLayout.addWidget(self.comboCTScanType)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbCTScanImg = QtWidgets.QLabel(CTScanPatient)
        self.lbCTScanImg.setMinimumSize(QtCore.QSize(384, 384))
        self.lbCTScanImg.setMaximumSize(QtCore.QSize(384, 384))
        self.lbCTScanImg.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbCTScanImg.setText("")
        self.lbCTScanImg.setObjectName("lbCTScanImg")
        self.verticalLayout.addWidget(self.lbCTScanImg)
        self.hSlider = QtWidgets.QSlider(CTScanPatient)
        self.hSlider.setMinimumSize(QtCore.QSize(384, 0))
        self.hSlider.setMaximumSize(QtCore.QSize(384, 16777215))
        self.hSlider.setMinimum(1)
        self.hSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hSlider.setObjectName("hSlider")
        self.verticalLayout.addWidget(self.hSlider)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CTScanPatient)
        QtCore.QMetaObject.connectSlotsByName(CTScanPatient)

    def retranslateUi(self, CTScanPatient):
        _translate = QtCore.QCoreApplication.translate
        CTScanPatient.setWindowTitle(_translate("CTScanPatient", "Frame"))
        self.label.setText(_translate("CTScanPatient", "Loại Chụp CT:"))
        self.comboCTScanType.setItemText(0, _translate("CTScanPatient", "Sọ Não"))
        self.comboCTScanType.setItemText(1, _translate("CTScanPatient", "Phổi"))
        self.comboCTScanType.setItemText(2, _translate("CTScanPatient", "Xương"))
        self.comboCTScanType.setItemText(3, _translate("CTScanPatient", "Ổ Bụng"))
