# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\A_Đồ Án_Endgames\Dev\eHealth_Version1.0_11_19_2021_1_58_pm_Debug\GUI\Design\UI_StatisticCovid.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticCovid(object):
    def setupUi(self, StatisticCovid):
        StatisticCovid.setObjectName("StatisticCovid")
        StatisticCovid.resize(1200, 611)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(StatisticCovid)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout_2.addLayout(self.mainLayout)

        self.retranslateUi(StatisticCovid)
        QtCore.QMetaObject.connectSlotsByName(StatisticCovid)

    def retranslateUi(self, StatisticCovid):
        _translate = QtCore.QCoreApplication.translate
        StatisticCovid.setWindowTitle(_translate("StatisticCovid", "Frame"))
