# Form implementation generated from reading ui file 'e:\A_Do_An_Endgames\Dev\eHealth_Version1.0_11_19_2021_1_58_pm_Debug\GUI\Design\UI_UltraSonicPatient.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UltraSonicPatient(object):
    def setupUi(self, UltraSonicPatient):
        UltraSonicPatient.setObjectName("UltraSonicPatient")
        UltraSonicPatient.resize(420, 483)
        UltraSonicPatient.setMinimumSize(QtCore.QSize(420, 483))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(UltraSonicPatient)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(UltraSonicPatient)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboUltraSonicType = QtWidgets.QComboBox(UltraSonicPatient)
        self.comboUltraSonicType.setMinimumSize(QtCore.QSize(268, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboUltraSonicType.setFont(font)
        self.comboUltraSonicType.setObjectName("comboUltraSonicType")
        self.comboUltraSonicType.addItem("")
        self.comboUltraSonicType.addItem("")
        self.comboUltraSonicType.addItem("")
        self.horizontalLayout.addWidget(self.comboUltraSonicType)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbUltraSonicImg = QtWidgets.QLabel(UltraSonicPatient)
        self.lbUltraSonicImg.setMinimumSize(QtCore.QSize(384, 384))
        self.lbUltraSonicImg.setMaximumSize(QtCore.QSize(384, 384))
        self.lbUltraSonicImg.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbUltraSonicImg.setText("")
        self.lbUltraSonicImg.setObjectName("lbUltraSonicImg")
        self.verticalLayout.addWidget(self.lbUltraSonicImg)
        self.hSlider = QtWidgets.QSlider(UltraSonicPatient)
        self.hSlider.setMinimumSize(QtCore.QSize(384, 0))
        self.hSlider.setMaximumSize(QtCore.QSize(384, 16777215))
        self.hSlider.setMinimum(1)
        self.hSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hSlider.setObjectName("hSlider")
        self.verticalLayout.addWidget(self.hSlider)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(UltraSonicPatient)
        QtCore.QMetaObject.connectSlotsByName(UltraSonicPatient)

    def retranslateUi(self, UltraSonicPatient):
        _translate = QtCore.QCoreApplication.translate
        UltraSonicPatient.setWindowTitle(_translate("UltraSonicPatient", "Frame"))
        self.label.setText(_translate("UltraSonicPatient", "Loại Siêu Âm:"))
        self.comboUltraSonicType.setItemText(0, _translate("UltraSonicPatient", "Tim"))
        self.comboUltraSonicType.setItemText(1, _translate("UltraSonicPatient", "Thai Nhi"))
        self.comboUltraSonicType.setItemText(2, _translate("UltraSonicPatient", "Gan Mật"))
