# Form implementation generated from reading ui file 'e:\A_Do_An_Endgames\Dev\eHealth_Version1.0_11_19_2021_1_58_pm_Debug\GUI\Design\UI_XRayPatient.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_XRayPaitient(object):
    def setupUi(self, XRayPaitient):
        XRayPaitient.setObjectName("XRayPaitient")
        XRayPaitient.resize(678, 484)
        XRayPaitient.setMinimumSize(QtCore.QSize(540, 353))
        XRayPaitient.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(12)
        XRayPaitient.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(XRayPaitient)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(XRayPaitient)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboXRayType = QtWidgets.QComboBox(XRayPaitient)
        self.comboXRayType.setMinimumSize(QtCore.QSize(268, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboXRayType.setFont(font)
        self.comboXRayType.setObjectName("comboXRayType")
        self.comboXRayType.addItem("")
        self.comboXRayType.addItem("")
        self.comboXRayType.addItem("")
        self.comboXRayType.addItem("")
        self.horizontalLayout.addWidget(self.comboXRayType)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(XRayPaitient)
        self.scrollArea.setStyleSheet("background-color: #00111d;\n"
"    color: #000000;\n"
"    border-color: #000000;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 641, 818))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbXRayImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbXRayImg.setMinimumSize(QtCore.QSize(622, 800))
        self.lbXRayImg.setMaximumSize(QtCore.QSize(622, 800))
        self.lbXRayImg.setStyleSheet("QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #656565;\n"
"\n"
"}")
        self.lbXRayImg.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbXRayImg.setText("")
        self.lbXRayImg.setObjectName("lbXRayImg")
        self.verticalLayout.addWidget(self.lbXRayImg)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btDiagnoseAI = QtWidgets.QPushButton(XRayPaitient)
        self.btDiagnoseAI.setMinimumSize(QtCore.QSize(0, 30))
        self.btDiagnoseAI.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btDiagnoseAI.setFont(font)
        self.btDiagnoseAI.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btDiagnoseAI.setObjectName("btDiagnoseAI")
        self.horizontalLayout_3.addWidget(self.btDiagnoseAI)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(XRayPaitient)
        QtCore.QMetaObject.connectSlotsByName(XRayPaitient)

    def retranslateUi(self, XRayPaitient):
        _translate = QtCore.QCoreApplication.translate
        XRayPaitient.setWindowTitle(_translate("XRayPaitient", "Frame"))
        self.label.setText(_translate("XRayPaitient", "Loại Chụp X - Quang:"))
        self.comboXRayType.setItemText(0, _translate("XRayPaitient", "Phổi"))
        self.comboXRayType.setItemText(1, _translate("XRayPaitient", "Cột Sống"))
        self.comboXRayType.setItemText(2, _translate("XRayPaitient", "Xương"))
        self.comboXRayType.setItemText(3, _translate("XRayPaitient", "Tuyến Vú"))
        self.btDiagnoseAI.setText(_translate("XRayPaitient", "Bật Hỗ Trợ Chẩn Đoán"))
