# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/Design/UI_TestPatient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestPaitient(object):
    def setupUi(self, TestPaitient):
        TestPaitient.setObjectName("TestPaitient")
        TestPaitient.resize(678, 484)
        TestPaitient.setMinimumSize(QtCore.QSize(540, 353))
        TestPaitient.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(12)
        TestPaitient.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TestPaitient)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(TestPaitient)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboTestType = QtWidgets.QComboBox(TestPaitient)
        self.comboTestType.setMinimumSize(QtCore.QSize(268, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboTestType.setFont(font)
        self.comboTestType.setObjectName("comboTestType")
        self.comboTestType.addItem("")
        self.comboTestType.addItem("")
        self.comboTestType.addItem("")
        self.comboTestType.addItem("")
        self.comboTestType.addItem("")
        self.horizontalLayout.addWidget(self.comboTestType)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(TestPaitient)
        self.scrollArea.setStyleSheet("background-color: #00111d;\n"
"    color: #000000;\n"
"    border-color: #000000;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 641, 818))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbTestImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbTestImg.setMinimumSize(QtCore.QSize(622, 800))
        self.lbTestImg.setMaximumSize(QtCore.QSize(622, 800))
        self.lbTestImg.setStyleSheet("QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #656565;\n"
"\n"
"}")
        self.lbTestImg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbTestImg.setText("")
        self.lbTestImg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbTestImg.setObjectName("lbTestImg")
        self.verticalLayout.addWidget(self.lbTestImg)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(TestPaitient)
        QtCore.QMetaObject.connectSlotsByName(TestPaitient)

    def retranslateUi(self, TestPaitient):
        _translate = QtCore.QCoreApplication.translate
        TestPaitient.setWindowTitle(_translate("TestPaitient", "Frame"))
        self.label.setText(_translate("TestPaitient", "Loại Xét Nghiệm:"))
        self.comboTestType.setItemText(0, _translate("TestPaitient", "Máu"))
        self.comboTestType.setItemText(1, _translate("TestPaitient", "Nước Tiểu"))
        self.comboTestType.setItemText(2, _translate("TestPaitient", "SARS - COV - 2"))
        self.comboTestType.setItemText(3, _translate("TestPaitient", "Sinh Thiết"))
        self.comboTestType.setItemText(4, _translate("TestPaitient", "CRP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestPaitient = QtWidgets.QFrame()
    ui = Ui_TestPaitient()
    ui.setupUi(TestPaitient)
    TestPaitient.show()
    sys.exit(app.exec_())
