# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/Design/UI_XRay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XRay(object):
    def setupUi(self, XRay):
        XRay.setObjectName("XRay")
        XRay.resize(1200, 611)
        font = QtGui.QFont()
        font.setPointSize(12)
        XRay.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(XRay)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(XRay)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txtSearch = QtWidgets.QLineEdit(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtSearch.setFont(font)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout_2.addWidget(self.txtSearch)
        self.btSearch = QtWidgets.QPushButton(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btSearch.setFont(font)
        self.btSearch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSearch.setObjectName("btSearch")
        self.horizontalLayout_2.addWidget(self.btSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioBTIDPatient = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.radioBTIDPatient.setFont(font)
        self.radioBTIDPatient.setObjectName("radioBTIDPatient")
        self.verticalLayout.addWidget(self.radioBTIDPatient)
        self.radioBTFullName = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioBTFullName.setFont(font)
        self.radioBTFullName.setObjectName("radioBTFullName")
        self.verticalLayout.addWidget(self.radioBTFullName)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboTypeXray = QtWidgets.QComboBox(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboTypeXray.setFont(font)
        self.comboTypeXray.setObjectName("comboTypeXray")
        self.comboTypeXray.addItem("")
        self.comboTypeXray.addItem("")
        self.comboTypeXray.addItem("")
        self.comboTypeXray.addItem("")
        self.horizontalLayout_3.addWidget(self.comboTypeXray)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.dataTabPatient = QtWidgets.QTableWidget(XRay)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.dataTabPatient.setFont(font)
        self.dataTabPatient.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dataTabPatient.setObjectName("dataTabPatient")
        self.dataTabPatient.setColumnCount(4)
        self.dataTabPatient.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dataTabPatient.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTabPatient.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTabPatient.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTabPatient.setHorizontalHeaderItem(3, item)
        self.dataTabPatient.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_2.addWidget(self.dataTabPatient)
        self.checkAllPatient = QtWidgets.QCheckBox(XRay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkAllPatient.setFont(font)
        self.checkAllPatient.setObjectName("checkAllPatient")
        self.verticalLayout_2.addWidget(self.checkAllPatient)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btUpload = QtWidgets.QPushButton(XRay)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btUpload.setFont(font)
        self.btUpload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btUpload.setObjectName("btUpload")
        self.horizontalLayout_4.addWidget(self.btUpload)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(3, 7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(XRay)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 640, 844))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: #00111d;\n"
"    color: #000000;\n"
"    border-color: #000000;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbPatient = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbPatient.setMinimumSize(QtCore.QSize(0, 20))
        self.lbPatient.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbPatient.setFont(font)
        self.lbPatient.setStyleSheet("QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #656565;\n"
"\n"
"}")
        self.lbPatient.setObjectName("lbPatient")
        self.verticalLayout_3.addWidget(self.lbPatient)
        self.lbXrayImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbXrayImg.setMinimumSize(QtCore.QSize(622, 800))
        self.lbXrayImg.setMaximumSize(QtCore.QSize(622, 800))
        self.lbXrayImg.setStyleSheet("QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #656565;\n"
"\n"
"}")
        self.lbXrayImg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbXrayImg.setText("")
        self.lbXrayImg.setObjectName("lbXrayImg")
        self.verticalLayout_3.addWidget(self.lbXrayImg)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)

        self.retranslateUi(XRay)
        QtCore.QMetaObject.connectSlotsByName(XRay)

    def retranslateUi(self, XRay):
        _translate = QtCore.QCoreApplication.translate
        XRay.setWindowTitle(_translate("XRay", "Frame"))
        self.label.setText(_translate("XRay", "CHỤP X - QUANG"))
        self.label_5.setText(_translate("XRay", "Tìm Kiếm Bệnh Nhân:"))
        self.btSearch.setText(_translate("XRay", "Tìm Kiếm"))
        self.groupBox.setTitle(_translate("XRay", "Tìm Kiếm Theo"))
        self.radioBTIDPatient.setText(_translate("XRay", "Mã Bệnh Nhân"))
        self.radioBTFullName.setText(_translate("XRay", "Tên Bệnh Nhân"))
        self.label_4.setText(_translate("XRay", "Loại Chụp X - Quang:"))
        self.comboTypeXray.setItemText(0, _translate("XRay", "Phổi"))
        self.comboTypeXray.setItemText(1, _translate("XRay", "Cột Sống"))
        self.comboTypeXray.setItemText(2, _translate("XRay", "Xương"))
        self.comboTypeXray.setItemText(3, _translate("XRay", "Tuyến Vú"))
        item = self.dataTabPatient.horizontalHeaderItem(0)
        item.setText(_translate("XRay", "Mã Bệnh Nhân"))
        item = self.dataTabPatient.horizontalHeaderItem(1)
        item.setText(_translate("XRay", "Tên Bệnh Nhân"))
        item = self.dataTabPatient.horizontalHeaderItem(2)
        item.setText(_translate("XRay", "Loại Chụp X - Quang"))
        item = self.dataTabPatient.horizontalHeaderItem(3)
        item.setText(_translate("XRay", "Trạng Thái"))
        self.checkAllPatient.setText(_translate("XRay", "Hiển Thị Tất Cả Bệnh Nhân"))
        self.btUpload.setText(_translate("XRay", "Cập Nhật\n"
"Kết Quả Chụp"))
        self.lbPatient.setText(_translate("XRay", "Bệnh Nhân: IDPatient - FullName"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XRay = QtWidgets.QFrame()
    ui = Ui_XRay()
    ui.setupUi(XRay)
    XRay.show()
    sys.exit(app.exec_())
